//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.WebServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Messenger.WebServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Envelope xmlns=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:wsse=&quot;http://schemas.xmlsoap.org/ws/2003/06/secext&quot; xmlns:saml=&quot;urn:oasis:names:tc:SAML:1.0:assertion&quot; xmlns:wsp=&quot;http://schemas.xmlsoap.org/ws/2002/12/policy&quot; xmlns:wsu=&quot;http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd&quot; xmlns:wsa=&quot;http://schemas.xmlsoap.org/ws/2004/03/addressing&quot; xmlns:wssc=&quot;http://schemas.xmlsoap.org/ws/2004/04/sc&quot; xmlns:wst=&quot;http://schemas.xmlsoap.org/ws/2004/04/trust&quot;&gt;
        ///  &lt;Header&gt;
        ///    &lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthenticationRequest {
            get {
                return ResourceManager.GetString("AuthenticationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:soapenc=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot;&gt;
        ///  &lt;soap:Header&gt;
        ///    &lt;ABApplicationHeader xmlns=&quot;http://www.msn.com/webservices/AddressBook&quot;&gt;
        ///      &lt;ApplicationId&gt;
        ///        CFE80F9D-180F-4399-82AB-413F33A1FA11
        ///      &lt;/ApplicationId&gt;
        ///      &lt;IsMigration&gt;
        ///        {0}
        ///      &lt;/IsMigration&gt;
        ///      &lt;PartnerScenario&gt;
        ///        Initia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContactRequest {
            get {
                return ResourceManager.GetString("ContactRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;View xmlns=&quot;http://www.msn.com/webservices/AddressBook&quot;&gt;Full&lt;/View&gt;
        ///&lt;deltasOnly xmlns=&quot;http://www.msn.com/webservices/AddressBook&quot;&gt;
        ///  {0}
        ///&lt;/deltasOnly&gt;
        ///&lt;lastChange xmlns=&quot;http://www.msn.com/webservices/AddressBook&quot;&gt;
        ///  {1}
        ///&lt;/lastChange&gt;.
        /// </summary>
        internal static string MembershipLastChange {
            get {
                return ResourceManager.GetString("MembershipLastChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;soap:Header xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///    &lt;ABApplicationHeader xmlns=&quot;http://www.msn.com/webservices/AddressBook&quot;&gt;
        ///      &lt;ApplicationId xmlns=&quot;http://www.msn.com/webservices/AddressBook&quot;&gt;CFE80F9D-180F-4399-82AB-413F33A1FA11&lt;/ApplicationId&gt;
        ///      &lt;IsMigration xmlns=&quot;http://www.msn.com/webservices/AddressBook&quot;&gt;{0}&lt;/IsMigration&gt;
        ///      &lt;PartnerScenario xmlns=&quot;http: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MembershipRequest {
            get {
                return ResourceManager.GetString("MembershipRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;wst:RequestSecurityToken Id=&quot;RST{0}&quot;&gt;
        ///  &lt;wst:RequestType&gt;http://schemas.xmlsoap.org/ws/2004/04/security/trust/Issue&lt;/wst:RequestType&gt;
        ///  &lt;wsp:AppliesTo&gt;
        ///    &lt;wsa:EndpointReference&gt;
        ///      &lt;wsa:Address&gt;{1}&lt;/wsa:Address&gt;
        ///    &lt;/wsa:EndpointReference&gt;
        ///  &lt;/wsp:AppliesTo&gt;
        ///  &lt;wsse:PolicyReference URI=&quot;{2}&quot;&gt;&lt;/wsse:PolicyReference&gt;
        ///&lt;/wst:RequestSecurityToken&gt;.
        /// </summary>
        internal static string SecurityToken {
            get {
                return ResourceManager.GetString("SecurityToken", resourceCulture);
            }
        }
    }
}
